#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : abseil-cpp
Version  : 20210324.2
Release  : 1
URL      : https://github.com/abseil/abseil-cpp/archive/20210324.2/abseil-cpp-20210324.2.tar.gz
Source0  : https://github.com/abseil/abseil-cpp/archive/20210324.2/abseil-cpp-20210324.2.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: abseil-cpp-lib = %{version}-%{release}
Requires: abseil-cpp-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : glibc-dev

%description
# Abseil - C++ Common Libraries
The repository contains the Abseil C++ library code. Abseil is an open-source
collection of C++ code (compliant to C++11) designed to augment the C++
standard library.

%package dev
Summary: dev components for the abseil-cpp package.
Group: Development
Requires: abseil-cpp-lib = %{version}-%{release}
Provides: abseil-cpp-devel = %{version}-%{release}
Requires: abseil-cpp = %{version}-%{release}

%description dev
dev components for the abseil-cpp package.


%package lib
Summary: lib components for the abseil-cpp package.
Group: Libraries
Requires: abseil-cpp-license = %{version}-%{release}

%description lib
lib components for the abseil-cpp package.


%package license
Summary: license components for the abseil-cpp package.
Group: Default

%description license
license components for the abseil-cpp package.


%prep
%setup -q -n abseil-cpp-20210324.2
cd %{_builddir}/abseil-cpp-20210324.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1633131260
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1633131260
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/abseil-cpp
cp %{_builddir}/abseil-cpp-20210324.2/LICENSE %{buildroot}/usr/share/package-licenses/abseil-cpp/77ca6ddbb42e1c1c589a0874f0ad28b7da4cccbb
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/absl/algorithm/algorithm.h
/usr/include/absl/algorithm/container.h
/usr/include/absl/base/attributes.h
/usr/include/absl/base/call_once.h
/usr/include/absl/base/casts.h
/usr/include/absl/base/config.h
/usr/include/absl/base/const_init.h
/usr/include/absl/base/dynamic_annotations.h
/usr/include/absl/base/internal/atomic_hook.h
/usr/include/absl/base/internal/atomic_hook_test_helper.h
/usr/include/absl/base/internal/cycleclock.h
/usr/include/absl/base/internal/direct_mmap.h
/usr/include/absl/base/internal/dynamic_annotations.h
/usr/include/absl/base/internal/endian.h
/usr/include/absl/base/internal/errno_saver.h
/usr/include/absl/base/internal/exception_safety_testing.h
/usr/include/absl/base/internal/exception_testing.h
/usr/include/absl/base/internal/exponential_biased.h
/usr/include/absl/base/internal/fast_type_id.h
/usr/include/absl/base/internal/hide_ptr.h
/usr/include/absl/base/internal/identity.h
/usr/include/absl/base/internal/inline_variable.h
/usr/include/absl/base/internal/inline_variable_testing.h
/usr/include/absl/base/internal/invoke.h
/usr/include/absl/base/internal/low_level_alloc.h
/usr/include/absl/base/internal/low_level_scheduling.h
/usr/include/absl/base/internal/per_thread_tls.h
/usr/include/absl/base/internal/periodic_sampler.h
/usr/include/absl/base/internal/pretty_function.h
/usr/include/absl/base/internal/raw_logging.h
/usr/include/absl/base/internal/scheduling_mode.h
/usr/include/absl/base/internal/scoped_set_env.h
/usr/include/absl/base/internal/spinlock.h
/usr/include/absl/base/internal/spinlock_akaros.inc
/usr/include/absl/base/internal/spinlock_linux.inc
/usr/include/absl/base/internal/spinlock_posix.inc
/usr/include/absl/base/internal/spinlock_wait.h
/usr/include/absl/base/internal/spinlock_win32.inc
/usr/include/absl/base/internal/strerror.h
/usr/include/absl/base/internal/sysinfo.h
/usr/include/absl/base/internal/thread_annotations.h
/usr/include/absl/base/internal/thread_identity.h
/usr/include/absl/base/internal/throw_delegate.h
/usr/include/absl/base/internal/tsan_mutex_interface.h
/usr/include/absl/base/internal/unaligned_access.h
/usr/include/absl/base/internal/unscaledcycleclock.h
/usr/include/absl/base/log_severity.h
/usr/include/absl/base/macros.h
/usr/include/absl/base/optimization.h
/usr/include/absl/base/options.h
/usr/include/absl/base/policy_checks.h
/usr/include/absl/base/port.h
/usr/include/absl/base/thread_annotations.h
/usr/include/absl/cleanup/cleanup.h
/usr/include/absl/cleanup/internal/cleanup.h
/usr/include/absl/container/btree_map.h
/usr/include/absl/container/btree_set.h
/usr/include/absl/container/btree_test.h
/usr/include/absl/container/fixed_array.h
/usr/include/absl/container/flat_hash_map.h
/usr/include/absl/container/flat_hash_set.h
/usr/include/absl/container/inlined_vector.h
/usr/include/absl/container/internal/btree.h
/usr/include/absl/container/internal/btree_container.h
/usr/include/absl/container/internal/common.h
/usr/include/absl/container/internal/compressed_tuple.h
/usr/include/absl/container/internal/container_memory.h
/usr/include/absl/container/internal/counting_allocator.h
/usr/include/absl/container/internal/hash_function_defaults.h
/usr/include/absl/container/internal/hash_generator_testing.h
/usr/include/absl/container/internal/hash_policy_testing.h
/usr/include/absl/container/internal/hash_policy_traits.h
/usr/include/absl/container/internal/hashtable_debug.h
/usr/include/absl/container/internal/hashtable_debug_hooks.h
/usr/include/absl/container/internal/hashtablez_sampler.h
/usr/include/absl/container/internal/have_sse.h
/usr/include/absl/container/internal/inlined_vector.h
/usr/include/absl/container/internal/layout.h
/usr/include/absl/container/internal/node_hash_policy.h
/usr/include/absl/container/internal/raw_hash_map.h
/usr/include/absl/container/internal/raw_hash_set.h
/usr/include/absl/container/internal/test_instance_tracker.h
/usr/include/absl/container/internal/tracked.h
/usr/include/absl/container/internal/unordered_map_constructor_test.h
/usr/include/absl/container/internal/unordered_map_lookup_test.h
/usr/include/absl/container/internal/unordered_map_members_test.h
/usr/include/absl/container/internal/unordered_map_modifiers_test.h
/usr/include/absl/container/internal/unordered_set_constructor_test.h
/usr/include/absl/container/internal/unordered_set_lookup_test.h
/usr/include/absl/container/internal/unordered_set_members_test.h
/usr/include/absl/container/internal/unordered_set_modifiers_test.h
/usr/include/absl/container/node_hash_map.h
/usr/include/absl/container/node_hash_set.h
/usr/include/absl/debugging/failure_signal_handler.h
/usr/include/absl/debugging/internal/address_is_readable.h
/usr/include/absl/debugging/internal/demangle.h
/usr/include/absl/debugging/internal/elf_mem_image.h
/usr/include/absl/debugging/internal/examine_stack.h
/usr/include/absl/debugging/internal/stack_consumption.h
/usr/include/absl/debugging/internal/stacktrace_aarch64-inl.inc
/usr/include/absl/debugging/internal/stacktrace_arm-inl.inc
/usr/include/absl/debugging/internal/stacktrace_config.h
/usr/include/absl/debugging/internal/stacktrace_generic-inl.inc
/usr/include/absl/debugging/internal/stacktrace_powerpc-inl.inc
/usr/include/absl/debugging/internal/stacktrace_unimplemented-inl.inc
/usr/include/absl/debugging/internal/stacktrace_win32-inl.inc
/usr/include/absl/debugging/internal/stacktrace_x86-inl.inc
/usr/include/absl/debugging/internal/symbolize.h
/usr/include/absl/debugging/internal/vdso_support.h
/usr/include/absl/debugging/leak_check.h
/usr/include/absl/debugging/stacktrace.h
/usr/include/absl/debugging/symbolize.h
/usr/include/absl/debugging/symbolize_darwin.inc
/usr/include/absl/debugging/symbolize_elf.inc
/usr/include/absl/debugging/symbolize_unimplemented.inc
/usr/include/absl/debugging/symbolize_win32.inc
/usr/include/absl/flags/commandlineflag.h
/usr/include/absl/flags/config.h
/usr/include/absl/flags/declare.h
/usr/include/absl/flags/flag.h
/usr/include/absl/flags/internal/commandlineflag.h
/usr/include/absl/flags/internal/flag.h
/usr/include/absl/flags/internal/parse.h
/usr/include/absl/flags/internal/path_util.h
/usr/include/absl/flags/internal/private_handle_accessor.h
/usr/include/absl/flags/internal/program_name.h
/usr/include/absl/flags/internal/registry.h
/usr/include/absl/flags/internal/sequence_lock.h
/usr/include/absl/flags/internal/usage.h
/usr/include/absl/flags/marshalling.h
/usr/include/absl/flags/parse.h
/usr/include/absl/flags/reflection.h
/usr/include/absl/flags/usage.h
/usr/include/absl/flags/usage_config.h
/usr/include/absl/functional/bind_front.h
/usr/include/absl/functional/function_ref.h
/usr/include/absl/functional/internal/front_binder.h
/usr/include/absl/functional/internal/function_ref.h
/usr/include/absl/hash/hash.h
/usr/include/absl/hash/hash_testing.h
/usr/include/absl/hash/internal/city.h
/usr/include/absl/hash/internal/hash.h
/usr/include/absl/hash/internal/spy_hash_state.h
/usr/include/absl/hash/internal/wyhash.h
/usr/include/absl/memory/memory.h
/usr/include/absl/meta/type_traits.h
/usr/include/absl/numeric/bits.h
/usr/include/absl/numeric/int128.h
/usr/include/absl/numeric/int128_have_intrinsic.inc
/usr/include/absl/numeric/int128_no_intrinsic.inc
/usr/include/absl/numeric/internal/bits.h
/usr/include/absl/numeric/internal/representation.h
/usr/include/absl/random/bernoulli_distribution.h
/usr/include/absl/random/beta_distribution.h
/usr/include/absl/random/bit_gen_ref.h
/usr/include/absl/random/discrete_distribution.h
/usr/include/absl/random/distributions.h
/usr/include/absl/random/exponential_distribution.h
/usr/include/absl/random/gaussian_distribution.h
/usr/include/absl/random/internal/chi_square.h
/usr/include/absl/random/internal/distribution_caller.h
/usr/include/absl/random/internal/distribution_test_util.h
/usr/include/absl/random/internal/explicit_seed_seq.h
/usr/include/absl/random/internal/fast_uniform_bits.h
/usr/include/absl/random/internal/fastmath.h
/usr/include/absl/random/internal/generate_real.h
/usr/include/absl/random/internal/iostream_state_saver.h
/usr/include/absl/random/internal/mock_helpers.h
/usr/include/absl/random/internal/mock_overload_set.h
/usr/include/absl/random/internal/nanobenchmark.h
/usr/include/absl/random/internal/nonsecure_base.h
/usr/include/absl/random/internal/pcg_engine.h
/usr/include/absl/random/internal/platform.h
/usr/include/absl/random/internal/pool_urbg.h
/usr/include/absl/random/internal/randen.h
/usr/include/absl/random/internal/randen_detect.h
/usr/include/absl/random/internal/randen_engine.h
/usr/include/absl/random/internal/randen_hwaes.h
/usr/include/absl/random/internal/randen_slow.h
/usr/include/absl/random/internal/randen_traits.h
/usr/include/absl/random/internal/salted_seed_seq.h
/usr/include/absl/random/internal/seed_material.h
/usr/include/absl/random/internal/sequence_urbg.h
/usr/include/absl/random/internal/traits.h
/usr/include/absl/random/internal/uniform_helper.h
/usr/include/absl/random/internal/wide_multiply.h
/usr/include/absl/random/log_uniform_int_distribution.h
/usr/include/absl/random/mock_distributions.h
/usr/include/absl/random/mocking_bit_gen.h
/usr/include/absl/random/poisson_distribution.h
/usr/include/absl/random/random.h
/usr/include/absl/random/seed_gen_exception.h
/usr/include/absl/random/seed_sequences.h
/usr/include/absl/random/uniform_int_distribution.h
/usr/include/absl/random/uniform_real_distribution.h
/usr/include/absl/random/zipf_distribution.h
/usr/include/absl/status/internal/status_internal.h
/usr/include/absl/status/internal/statusor_internal.h
/usr/include/absl/status/status.h
/usr/include/absl/status/status_payload_printer.h
/usr/include/absl/status/statusor.h
/usr/include/absl/strings/ascii.h
/usr/include/absl/strings/charconv.h
/usr/include/absl/strings/cord.h
/usr/include/absl/strings/cord_test_helpers.h
/usr/include/absl/strings/escaping.h
/usr/include/absl/strings/internal/char_map.h
/usr/include/absl/strings/internal/charconv_bigint.h
/usr/include/absl/strings/internal/charconv_parse.h
/usr/include/absl/strings/internal/cord_internal.h
/usr/include/absl/strings/internal/cord_rep_flat.h
/usr/include/absl/strings/internal/cord_rep_ring.h
/usr/include/absl/strings/internal/cord_rep_ring_reader.h
/usr/include/absl/strings/internal/escaping.h
/usr/include/absl/strings/internal/escaping_test_common.h
/usr/include/absl/strings/internal/memutil.h
/usr/include/absl/strings/internal/numbers_test_common.h
/usr/include/absl/strings/internal/ostringstream.h
/usr/include/absl/strings/internal/pow10_helper.h
/usr/include/absl/strings/internal/resize_uninitialized.h
/usr/include/absl/strings/internal/stl_type_traits.h
/usr/include/absl/strings/internal/str_format/arg.h
/usr/include/absl/strings/internal/str_format/bind.h
/usr/include/absl/strings/internal/str_format/checker.h
/usr/include/absl/strings/internal/str_format/extension.h
/usr/include/absl/strings/internal/str_format/float_conversion.h
/usr/include/absl/strings/internal/str_format/output.h
/usr/include/absl/strings/internal/str_format/parser.h
/usr/include/absl/strings/internal/str_join_internal.h
/usr/include/absl/strings/internal/str_split_internal.h
/usr/include/absl/strings/internal/string_constant.h
/usr/include/absl/strings/internal/utf8.h
/usr/include/absl/strings/match.h
/usr/include/absl/strings/numbers.h
/usr/include/absl/strings/str_cat.h
/usr/include/absl/strings/str_format.h
/usr/include/absl/strings/str_join.h
/usr/include/absl/strings/str_replace.h
/usr/include/absl/strings/str_split.h
/usr/include/absl/strings/string_view.h
/usr/include/absl/strings/strip.h
/usr/include/absl/strings/substitute.h
/usr/include/absl/synchronization/barrier.h
/usr/include/absl/synchronization/blocking_counter.h
/usr/include/absl/synchronization/internal/create_thread_identity.h
/usr/include/absl/synchronization/internal/futex.h
/usr/include/absl/synchronization/internal/graphcycles.h
/usr/include/absl/synchronization/internal/kernel_timeout.h
/usr/include/absl/synchronization/internal/per_thread_sem.h
/usr/include/absl/synchronization/internal/thread_pool.h
/usr/include/absl/synchronization/internal/waiter.h
/usr/include/absl/synchronization/mutex.h
/usr/include/absl/synchronization/notification.h
/usr/include/absl/time/civil_time.h
/usr/include/absl/time/clock.h
/usr/include/absl/time/internal/cctz/include/cctz/civil_time.h
/usr/include/absl/time/internal/cctz/include/cctz/civil_time_detail.h
/usr/include/absl/time/internal/cctz/include/cctz/time_zone.h
/usr/include/absl/time/internal/cctz/include/cctz/zone_info_source.h
/usr/include/absl/time/internal/cctz/src/time_zone_fixed.h
/usr/include/absl/time/internal/cctz/src/time_zone_if.h
/usr/include/absl/time/internal/cctz/src/time_zone_impl.h
/usr/include/absl/time/internal/cctz/src/time_zone_info.h
/usr/include/absl/time/internal/cctz/src/time_zone_libc.h
/usr/include/absl/time/internal/cctz/src/time_zone_posix.h
/usr/include/absl/time/internal/cctz/src/tzfile.h
/usr/include/absl/time/internal/get_current_time_chrono.inc
/usr/include/absl/time/internal/get_current_time_posix.inc
/usr/include/absl/time/internal/test_util.h
/usr/include/absl/time/internal/zoneinfo.inc
/usr/include/absl/time/time.h
/usr/include/absl/types/any.h
/usr/include/absl/types/bad_any_cast.h
/usr/include/absl/types/bad_optional_access.h
/usr/include/absl/types/bad_variant_access.h
/usr/include/absl/types/compare.h
/usr/include/absl/types/internal/conformance_aliases.h
/usr/include/absl/types/internal/conformance_archetype.h
/usr/include/absl/types/internal/conformance_profile.h
/usr/include/absl/types/internal/conformance_testing.h
/usr/include/absl/types/internal/conformance_testing_helpers.h
/usr/include/absl/types/internal/optional.h
/usr/include/absl/types/internal/parentheses.h
/usr/include/absl/types/internal/span.h
/usr/include/absl/types/internal/transform_args.h
/usr/include/absl/types/internal/variant.h
/usr/include/absl/types/optional.h
/usr/include/absl/types/span.h
/usr/include/absl/types/variant.h
/usr/include/absl/utility/utility.h
/usr/lib64/cmake/absl/abslConfig.cmake
/usr/lib64/cmake/absl/abslConfigVersion.cmake
/usr/lib64/cmake/absl/abslTargets-relwithdebinfo.cmake
/usr/lib64/cmake/absl/abslTargets.cmake
/usr/lib64/libabsl_bad_any_cast_impl.so
/usr/lib64/libabsl_bad_optional_access.so
/usr/lib64/libabsl_bad_variant_access.so
/usr/lib64/libabsl_base.so
/usr/lib64/libabsl_city.so
/usr/lib64/libabsl_civil_time.so
/usr/lib64/libabsl_cord.so
/usr/lib64/libabsl_debugging_internal.so
/usr/lib64/libabsl_demangle_internal.so
/usr/lib64/libabsl_examine_stack.so
/usr/lib64/libabsl_exponential_biased.so
/usr/lib64/libabsl_failure_signal_handler.so
/usr/lib64/libabsl_flags.so
/usr/lib64/libabsl_flags_commandlineflag.so
/usr/lib64/libabsl_flags_commandlineflag_internal.so
/usr/lib64/libabsl_flags_config.so
/usr/lib64/libabsl_flags_internal.so
/usr/lib64/libabsl_flags_marshalling.so
/usr/lib64/libabsl_flags_parse.so
/usr/lib64/libabsl_flags_private_handle_accessor.so
/usr/lib64/libabsl_flags_program_name.so
/usr/lib64/libabsl_flags_reflection.so
/usr/lib64/libabsl_flags_usage.so
/usr/lib64/libabsl_flags_usage_internal.so
/usr/lib64/libabsl_graphcycles_internal.so
/usr/lib64/libabsl_hash.so
/usr/lib64/libabsl_hashtablez_sampler.so
/usr/lib64/libabsl_int128.so
/usr/lib64/libabsl_leak_check.so
/usr/lib64/libabsl_leak_check_disable.so
/usr/lib64/libabsl_log_severity.so
/usr/lib64/libabsl_malloc_internal.so
/usr/lib64/libabsl_periodic_sampler.so
/usr/lib64/libabsl_random_distributions.so
/usr/lib64/libabsl_random_internal_distribution_test_util.so
/usr/lib64/libabsl_random_internal_platform.so
/usr/lib64/libabsl_random_internal_pool_urbg.so
/usr/lib64/libabsl_random_internal_randen.so
/usr/lib64/libabsl_random_internal_randen_hwaes.so
/usr/lib64/libabsl_random_internal_randen_hwaes_impl.so
/usr/lib64/libabsl_random_internal_randen_slow.so
/usr/lib64/libabsl_random_internal_seed_material.so
/usr/lib64/libabsl_random_seed_gen_exception.so
/usr/lib64/libabsl_random_seed_sequences.so
/usr/lib64/libabsl_raw_hash_set.so
/usr/lib64/libabsl_raw_logging_internal.so
/usr/lib64/libabsl_scoped_set_env.so
/usr/lib64/libabsl_spinlock_wait.so
/usr/lib64/libabsl_stacktrace.so
/usr/lib64/libabsl_status.so
/usr/lib64/libabsl_statusor.so
/usr/lib64/libabsl_str_format_internal.so
/usr/lib64/libabsl_strerror.so
/usr/lib64/libabsl_strings.so
/usr/lib64/libabsl_strings_internal.so
/usr/lib64/libabsl_symbolize.so
/usr/lib64/libabsl_synchronization.so
/usr/lib64/libabsl_throw_delegate.so
/usr/lib64/libabsl_time.so
/usr/lib64/libabsl_time_zone.so
/usr/lib64/libabsl_wyhash.so
/usr/lib64/pkgconfig/absl_algorithm.pc
/usr/lib64/pkgconfig/absl_algorithm_container.pc
/usr/lib64/pkgconfig/absl_any.pc
/usr/lib64/pkgconfig/absl_atomic_hook.pc
/usr/lib64/pkgconfig/absl_bad_any_cast.pc
/usr/lib64/pkgconfig/absl_bad_any_cast_impl.pc
/usr/lib64/pkgconfig/absl_bad_optional_access.pc
/usr/lib64/pkgconfig/absl_bad_variant_access.pc
/usr/lib64/pkgconfig/absl_base.pc
/usr/lib64/pkgconfig/absl_base_internal.pc
/usr/lib64/pkgconfig/absl_bind_front.pc
/usr/lib64/pkgconfig/absl_bits.pc
/usr/lib64/pkgconfig/absl_btree.pc
/usr/lib64/pkgconfig/absl_city.pc
/usr/lib64/pkgconfig/absl_civil_time.pc
/usr/lib64/pkgconfig/absl_cleanup.pc
/usr/lib64/pkgconfig/absl_cleanup_internal.pc
/usr/lib64/pkgconfig/absl_compare.pc
/usr/lib64/pkgconfig/absl_compressed_tuple.pc
/usr/lib64/pkgconfig/absl_config.pc
/usr/lib64/pkgconfig/absl_container_common.pc
/usr/lib64/pkgconfig/absl_container_memory.pc
/usr/lib64/pkgconfig/absl_cord.pc
/usr/lib64/pkgconfig/absl_core_headers.pc
/usr/lib64/pkgconfig/absl_counting_allocator.pc
/usr/lib64/pkgconfig/absl_debugging.pc
/usr/lib64/pkgconfig/absl_debugging_internal.pc
/usr/lib64/pkgconfig/absl_demangle_internal.pc
/usr/lib64/pkgconfig/absl_dynamic_annotations.pc
/usr/lib64/pkgconfig/absl_endian.pc
/usr/lib64/pkgconfig/absl_errno_saver.pc
/usr/lib64/pkgconfig/absl_examine_stack.pc
/usr/lib64/pkgconfig/absl_exponential_biased.pc
/usr/lib64/pkgconfig/absl_failure_signal_handler.pc
/usr/lib64/pkgconfig/absl_fast_type_id.pc
/usr/lib64/pkgconfig/absl_fixed_array.pc
/usr/lib64/pkgconfig/absl_flags.pc
/usr/lib64/pkgconfig/absl_flags_commandlineflag.pc
/usr/lib64/pkgconfig/absl_flags_commandlineflag_internal.pc
/usr/lib64/pkgconfig/absl_flags_config.pc
/usr/lib64/pkgconfig/absl_flags_internal.pc
/usr/lib64/pkgconfig/absl_flags_marshalling.pc
/usr/lib64/pkgconfig/absl_flags_parse.pc
/usr/lib64/pkgconfig/absl_flags_path_util.pc
/usr/lib64/pkgconfig/absl_flags_private_handle_accessor.pc
/usr/lib64/pkgconfig/absl_flags_program_name.pc
/usr/lib64/pkgconfig/absl_flags_reflection.pc
/usr/lib64/pkgconfig/absl_flags_usage.pc
/usr/lib64/pkgconfig/absl_flags_usage_internal.pc
/usr/lib64/pkgconfig/absl_flat_hash_map.pc
/usr/lib64/pkgconfig/absl_flat_hash_set.pc
/usr/lib64/pkgconfig/absl_function_ref.pc
/usr/lib64/pkgconfig/absl_graphcycles_internal.pc
/usr/lib64/pkgconfig/absl_hash.pc
/usr/lib64/pkgconfig/absl_hash_function_defaults.pc
/usr/lib64/pkgconfig/absl_hash_policy_traits.pc
/usr/lib64/pkgconfig/absl_hashtable_debug.pc
/usr/lib64/pkgconfig/absl_hashtable_debug_hooks.pc
/usr/lib64/pkgconfig/absl_hashtablez_sampler.pc
/usr/lib64/pkgconfig/absl_have_sse.pc
/usr/lib64/pkgconfig/absl_inlined_vector.pc
/usr/lib64/pkgconfig/absl_inlined_vector_internal.pc
/usr/lib64/pkgconfig/absl_int128.pc
/usr/lib64/pkgconfig/absl_kernel_timeout_internal.pc
/usr/lib64/pkgconfig/absl_layout.pc
/usr/lib64/pkgconfig/absl_leak_check.pc
/usr/lib64/pkgconfig/absl_leak_check_disable.pc
/usr/lib64/pkgconfig/absl_log_severity.pc
/usr/lib64/pkgconfig/absl_malloc_internal.pc
/usr/lib64/pkgconfig/absl_memory.pc
/usr/lib64/pkgconfig/absl_meta.pc
/usr/lib64/pkgconfig/absl_node_hash_map.pc
/usr/lib64/pkgconfig/absl_node_hash_policy.pc
/usr/lib64/pkgconfig/absl_node_hash_set.pc
/usr/lib64/pkgconfig/absl_numeric.pc
/usr/lib64/pkgconfig/absl_numeric_representation.pc
/usr/lib64/pkgconfig/absl_optional.pc
/usr/lib64/pkgconfig/absl_periodic_sampler.pc
/usr/lib64/pkgconfig/absl_pretty_function.pc
/usr/lib64/pkgconfig/absl_random_bit_gen_ref.pc
/usr/lib64/pkgconfig/absl_random_distributions.pc
/usr/lib64/pkgconfig/absl_random_internal_distribution_caller.pc
/usr/lib64/pkgconfig/absl_random_internal_distribution_test_util.pc
/usr/lib64/pkgconfig/absl_random_internal_fast_uniform_bits.pc
/usr/lib64/pkgconfig/absl_random_internal_fastmath.pc
/usr/lib64/pkgconfig/absl_random_internal_generate_real.pc
/usr/lib64/pkgconfig/absl_random_internal_iostream_state_saver.pc
/usr/lib64/pkgconfig/absl_random_internal_mock_helpers.pc
/usr/lib64/pkgconfig/absl_random_internal_nonsecure_base.pc
/usr/lib64/pkgconfig/absl_random_internal_pcg_engine.pc
/usr/lib64/pkgconfig/absl_random_internal_platform.pc
/usr/lib64/pkgconfig/absl_random_internal_pool_urbg.pc
/usr/lib64/pkgconfig/absl_random_internal_randen.pc
/usr/lib64/pkgconfig/absl_random_internal_randen_engine.pc
/usr/lib64/pkgconfig/absl_random_internal_randen_hwaes.pc
/usr/lib64/pkgconfig/absl_random_internal_randen_hwaes_impl.pc
/usr/lib64/pkgconfig/absl_random_internal_randen_slow.pc
/usr/lib64/pkgconfig/absl_random_internal_salted_seed_seq.pc
/usr/lib64/pkgconfig/absl_random_internal_seed_material.pc
/usr/lib64/pkgconfig/absl_random_internal_traits.pc
/usr/lib64/pkgconfig/absl_random_internal_uniform_helper.pc
/usr/lib64/pkgconfig/absl_random_internal_wide_multiply.pc
/usr/lib64/pkgconfig/absl_random_random.pc
/usr/lib64/pkgconfig/absl_random_seed_gen_exception.pc
/usr/lib64/pkgconfig/absl_random_seed_sequences.pc
/usr/lib64/pkgconfig/absl_raw_hash_map.pc
/usr/lib64/pkgconfig/absl_raw_hash_set.pc
/usr/lib64/pkgconfig/absl_raw_logging_internal.pc
/usr/lib64/pkgconfig/absl_scoped_set_env.pc
/usr/lib64/pkgconfig/absl_span.pc
/usr/lib64/pkgconfig/absl_spinlock_wait.pc
/usr/lib64/pkgconfig/absl_stacktrace.pc
/usr/lib64/pkgconfig/absl_status.pc
/usr/lib64/pkgconfig/absl_statusor.pc
/usr/lib64/pkgconfig/absl_str_format.pc
/usr/lib64/pkgconfig/absl_str_format_internal.pc
/usr/lib64/pkgconfig/absl_strerror.pc
/usr/lib64/pkgconfig/absl_strings.pc
/usr/lib64/pkgconfig/absl_strings_internal.pc
/usr/lib64/pkgconfig/absl_symbolize.pc
/usr/lib64/pkgconfig/absl_synchronization.pc
/usr/lib64/pkgconfig/absl_throw_delegate.pc
/usr/lib64/pkgconfig/absl_time.pc
/usr/lib64/pkgconfig/absl_time_zone.pc
/usr/lib64/pkgconfig/absl_type_traits.pc
/usr/lib64/pkgconfig/absl_utility.pc
/usr/lib64/pkgconfig/absl_variant.pc
/usr/lib64/pkgconfig/absl_wyhash.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libabsl_bad_any_cast_impl.so.2103.0.1
/usr/lib64/libabsl_bad_optional_access.so.2103.0.1
/usr/lib64/libabsl_bad_variant_access.so.2103.0.1
/usr/lib64/libabsl_base.so.2103.0.1
/usr/lib64/libabsl_city.so.2103.0.1
/usr/lib64/libabsl_civil_time.so.2103.0.1
/usr/lib64/libabsl_cord.so.2103.0.1
/usr/lib64/libabsl_debugging_internal.so.2103.0.1
/usr/lib64/libabsl_demangle_internal.so.2103.0.1
/usr/lib64/libabsl_examine_stack.so.2103.0.1
/usr/lib64/libabsl_exponential_biased.so.2103.0.1
/usr/lib64/libabsl_failure_signal_handler.so.2103.0.1
/usr/lib64/libabsl_flags.so.2103.0.1
/usr/lib64/libabsl_flags_commandlineflag.so.2103.0.1
/usr/lib64/libabsl_flags_commandlineflag_internal.so.2103.0.1
/usr/lib64/libabsl_flags_config.so.2103.0.1
/usr/lib64/libabsl_flags_internal.so.2103.0.1
/usr/lib64/libabsl_flags_marshalling.so.2103.0.1
/usr/lib64/libabsl_flags_parse.so.2103.0.1
/usr/lib64/libabsl_flags_private_handle_accessor.so.2103.0.1
/usr/lib64/libabsl_flags_program_name.so.2103.0.1
/usr/lib64/libabsl_flags_reflection.so.2103.0.1
/usr/lib64/libabsl_flags_usage.so.2103.0.1
/usr/lib64/libabsl_flags_usage_internal.so.2103.0.1
/usr/lib64/libabsl_graphcycles_internal.so.2103.0.1
/usr/lib64/libabsl_hash.so.2103.0.1
/usr/lib64/libabsl_hashtablez_sampler.so.2103.0.1
/usr/lib64/libabsl_int128.so.2103.0.1
/usr/lib64/libabsl_leak_check.so.2103.0.1
/usr/lib64/libabsl_leak_check_disable.so.2103.0.1
/usr/lib64/libabsl_log_severity.so.2103.0.1
/usr/lib64/libabsl_malloc_internal.so.2103.0.1
/usr/lib64/libabsl_periodic_sampler.so.2103.0.1
/usr/lib64/libabsl_random_distributions.so.2103.0.1
/usr/lib64/libabsl_random_internal_distribution_test_util.so.2103.0.1
/usr/lib64/libabsl_random_internal_platform.so.2103.0.1
/usr/lib64/libabsl_random_internal_pool_urbg.so.2103.0.1
/usr/lib64/libabsl_random_internal_randen.so.2103.0.1
/usr/lib64/libabsl_random_internal_randen_hwaes.so.2103.0.1
/usr/lib64/libabsl_random_internal_randen_hwaes_impl.so.2103.0.1
/usr/lib64/libabsl_random_internal_randen_slow.so.2103.0.1
/usr/lib64/libabsl_random_internal_seed_material.so.2103.0.1
/usr/lib64/libabsl_random_seed_gen_exception.so.2103.0.1
/usr/lib64/libabsl_random_seed_sequences.so.2103.0.1
/usr/lib64/libabsl_raw_hash_set.so.2103.0.1
/usr/lib64/libabsl_raw_logging_internal.so.2103.0.1
/usr/lib64/libabsl_scoped_set_env.so.2103.0.1
/usr/lib64/libabsl_spinlock_wait.so.2103.0.1
/usr/lib64/libabsl_stacktrace.so.2103.0.1
/usr/lib64/libabsl_status.so.2103.0.1
/usr/lib64/libabsl_statusor.so.2103.0.1
/usr/lib64/libabsl_str_format_internal.so.2103.0.1
/usr/lib64/libabsl_strerror.so.2103.0.1
/usr/lib64/libabsl_strings.so.2103.0.1
/usr/lib64/libabsl_strings_internal.so.2103.0.1
/usr/lib64/libabsl_symbolize.so.2103.0.1
/usr/lib64/libabsl_synchronization.so.2103.0.1
/usr/lib64/libabsl_throw_delegate.so.2103.0.1
/usr/lib64/libabsl_time.so.2103.0.1
/usr/lib64/libabsl_time_zone.so.2103.0.1
/usr/lib64/libabsl_wyhash.so.2103.0.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/abseil-cpp/77ca6ddbb42e1c1c589a0874f0ad28b7da4cccbb
